{{- if .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cme-{{ template "minion-ms.resourceName" . }}
data:
{{- range .Values.configmap.envMounted}}
{{ .key | indent 2}}: {{ toYaml .value | indent 4 }}
{{- end}}
{{- end}}