{{- if .Values.configmap }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: scv-{{ template "minion-ms.resourceName" . }}
data:
{{- range .Values.secret.volumeMounted}}
{{ .key | indent 2}}: {{ toYaml .value | b64enc | indent 4 }}
{{- end}}
{{- end}}